import Head from 'next/head';
import Empower from "../components/empower";
import Navbar from "../components/navbar";
import WhyKapable from "../components/whyKapable";
import Creative from '../components/creative';
import Course from '../components/course';
import Vision from "../components/vision";
import Parents from '../components/parents';
import Growth from '../components/growth';
import Experience from '../components/experience';
import Bonuses from '../components/bonuses';
import Faqs from '../components/faqs';
import Potential from '../components/potential';
import ContactUs from '../components/contactUs';
import CopyRights from '../components/copyRights';

export default function Home() {
  const checkBoxArr=["","","","","",""];

  const scrollToTop = () => {
    window.scrollTo({
      top: 500,
      behavior: 'smooth',
    });
  };
  
  return (
    <div>
      <Head>
        <title>Kapable | Cape of Confidence</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
          <div className='flex justify-center bg-[url("/assets/background2.png")] bg-no-repeat'>
            <div className='lg:w-[1024px] md:w-[768px] w-full px-4 md:px-0'>
              <Navbar/>
              <Empower checkBoxArr={checkBoxArr}/>
              <WhyKapable/>
              <Creative/>
            </div>
          </div>
          <div className='flex justify-center bg-[url("/assets/bacg.png")] bg-no-repeat'>
            <div className='lg:w-[1024px] md:w-[768px] w-full px-4 md:px-0'>
              <Course/>
              <Vision/>
            </div>
          </div>
            <Parents/>
          <div className='flex justify-center'>
            <div className='lg:w-[1024px] md:w-[768px] w-full px-4 md:px-0'>
              <Growth checkBoxArr={checkBoxArr}/>
            </div>
          </div>
          <Experience/>
          <div className='flex justify-center bg-[url("/assets/bacg.png")] bg-no-repeat'>
            <div className='lg:w-[1024px] md:w-[768px] w-full px-4 md:px-0'>
              <Bonuses/>
              <Faqs/>
            </div>
          </div>
          <Potential/>
          <div className='flex justify-center bg-[url("/assets/bacg.png")] bg-no-repeat'>
            <div className='lg:w-[1024px] md:w-[768px] w-full px-4 md:px-0'>
              <ContactUs/>
              <CopyRights/>
            </div>
          </div>
          <div type="button"  onClick={scrollToTop} className='text-white bg-gradient-to-r from-[#FA4A5F] to-[#227AEB] w-full py-4 px-2 md:px-4 rounded-t-lg text-base text-center md:hidden fixed bottom-0 font-semibold'>Enroll Now</div>
      </main>
    </div>
  )
}
